@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.carbonaracode.digibookycarbonara.members.MemberController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline


'nodes
subgraph cluster_1196949968 {
   	label=carbonaracode
	labeljust=l
	fillcolor="#ececec"
	style=filled

   subgraph cluster_1776094584 {
   	label=digibookycarbonara
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled

   AbstractMember1296305264[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AbstractMember</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   email: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   inss: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   name: Name [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- validateEmail(email: String)</TD></TR>
<TR><TD ALIGN="LEFT" >- validateInss(inss: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Address1296305264[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Address</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   city: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   postalCode: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   streetName: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   streetNumber: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- stringIsNotEmptyOrNull(string: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Author1398452287[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Author</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   authorFirstname: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   authorLastname: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ authorFirstname(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ authorLastname(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Book1398452287[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Book</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   author: Author [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   isbn: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   summary: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   title: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ newBuilder(): BookBuilder</TD></TR>
<TR><TD ALIGN="LEFT" >+ newBuilder(book: Book): BookBuilder</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

KeycloakService1165648183[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)KeycloakService</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   clientID: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   realmResource: RealmResource [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- addRole(user: UserResource, roleName: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ addUser(keycloakUserDTO: KeycloakUserDTO)</TD></TR>
<TR><TD ALIGN="LEFT" >- createCredentialRepresentation(password: String): CredentialRepresentation</TD></TR>
<TR><TD ALIGN="LEFT" >- createUser(keycloakUserDTO: KeycloakUserDTO): String</TD></TR>
<TR><TD ALIGN="LEFT" >- createUser(username: String): Response</TD></TR>
<TR><TD ALIGN="LEFT" >- createUserRepresentation(username: String): UserRepresentation</TD></TR>
<TR><TD ALIGN="LEFT" >- getRole(roleToAdd: String): RoleRepresentation</TD></TR>
<TR><TD ALIGN="LEFT" >- getUser(userId: String): UserResource</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

KeycloakUserDTO1165648183[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)KeycloakUserDTO</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   password: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   role: Role [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   userName: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ password(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ role(): Role</TD></TR>
<TR><TD ALIGN="LEFT" >+ userName(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

LentBook409788394[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)LentBook</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   dueDate: LocalDate [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   lendingID: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- calculateDueDate(): LocalDate</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Librarian2052539930[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Librarian</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Member1296305264[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Member</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   address: Address [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   lentBookList: List&lt;LentBook&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addLentBook(lentBook: LentBook)</TD></TR>
<TR><TD ALIGN="LEFT" >+ newBuilder(): MemberBuilder</TD></TR>
<TR><TD ALIGN="LEFT" >+ returnLentBook(lentBook: LentBook)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

MemberBuilder157299192[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)MemberBuilder</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   address: Address [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   email: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   inss: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   name: Name [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ build(): Member</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

MemberController1296305264[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)MemberController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   memberService: MemberService [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ registerNewMember(memberDto: MemberDTO): MemberDTO</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

MemberMapper1296305264[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)MemberMapper</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   logger: Logger [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># memberDtoToMember(memberDto: MemberDTO): Member</TD></TR>
<TR><TD ALIGN="LEFT" ># memberToMemberDto(member: Member): MemberDTO</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

MemberRepository1296305264[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)MemberRepository</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   logger: Logger [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   memberMap: Map&lt;String, Member&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ createAndInitializeMemberMap(): Map&lt;String, Member&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >- doesMemberExist(inss: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getMemberByInss(inss: String): Member</TD></TR>
<TR><TD ALIGN="LEFT" >- isNotEmpty(inss: String)</TD></TR>
<TR><TD ALIGN="LEFT" >- isNotNull(member: Member)</TD></TR>
<TR><TD ALIGN="LEFT" >- isNotNull(inss: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ register(member: Member)</TD></TR>
<TR><TD ALIGN="LEFT" >- validateEmail(member: Member)</TD></TR>
<TR><TD ALIGN="LEFT" >- validateInss(member: Member)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

MemberService1296305264[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)MemberService</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   keycloakService: KeycloakService [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   logger: Logger [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   memberMapper: MemberMapper [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   memberRepository: MemberRepository [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ registerNewMember(memberDto: MemberDTO)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Name1718269883[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Name</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   firstName: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   lastName: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- validateNameField(name: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
}
}

'edges
AbstractMember1296305264 -> Librarian2052539930[arrowhead=none, arrowtail=empty, dir=both];
AbstractMember1296305264 -> Member1296305264[arrowhead=none, arrowtail=empty, dir=both];
AbstractMember1296305264 -> Name1718269883[label="name
[0..1]"];
Book1398452287 -> Author1398452287[label="author
[0..1]"];
Book1398452287 -> LentBook409788394[arrowhead=none, arrowtail=empty, dir=both];
Member1296305264 -> Address1296305264[label="address
[0..1]"];
Member1296305264 -> LentBook409788394[label="lentBookList
[0..*]"];
MemberBuilder157299192 -> Address1296305264[label="address
[0..1]"];
MemberBuilder157299192 -> Name1718269883[label="name
[0..1]"];
MemberController1296305264 -> MemberService1296305264[label="memberService
[0..1]"];
MemberMapper1296305264 -> Member1296305264[label="memberDtoToMember() -> newBuilder()"];
MemberMapper1296305264 -> MemberBuilder157299192[label="memberDtoToMember() -> build()"];
MemberRepository1296305264 -> Member1296305264[label="memberMap
[0..*]"];
MemberRepository1296305264 -> MemberBuilder157299192[label="createAndInitializeMemberMap() -> build()"];
MemberService1296305264 -> KeycloakService1165648183[label="keycloakService
[0..1]"];
MemberService1296305264 -> MemberMapper1296305264[label="memberMapper
[0..1]"];
MemberService1296305264 -> MemberRepository1296305264[label="memberRepository
[0..1]"];

}
@enduml
